// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values for Lovable Cloud - env vars should be set automatically
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://myyfzsxyznvnrruubqgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eWZ6c3h5em52bnJydXVicWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4Mzc0MTUsImV4cCI6MjA4NDQxMzQxNX0.EwG0PHm8YukYe4XEqNemNb7gNO2bF42uSG3ZD9lyLcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
